### ISSUE TITLE
Instruction not viable for Win

### ISSUE THREAD

**Issue by fluviolobo** [onshape-public/apikey#22]
Hello,

I was wondering if the instructions below were not meant for Windows.
I Forked the repo. and made some modifications that allowed me to complete the setup process and ran the example python programs. I summarized the steps on a new version of the README file and created a new requirements-win.txt file (both are attached on the win-sol.zip).

[win-sol.zip](https://github.com/onshape-public/apikey/files/1413143/win-sol.zip)

Would this be useful to add to the main branch?
Am I missing something?

Thank you!

**Comment by awk** [comment]
Yes! this looks like a worthwhile set of changes! If you've forked the repo you can create a pull request here to get your changes back into this repo.  https://help.github.com/articles/about-pull-requests/ has some more details if you're not familiar with the Github pull request mechanisms.

**Comment by fluviolobo** [comment]
Let me make one more change on my README file and I will submit the pull request.

Thank you!
